/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logfile.reader;

import logfile.reader.reader.Reader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        try {
            new Reader(args[0]);
        } catch (ArrayIndexOutOfBoundsException e) {
            logger.error("No argument provided! Put file name as program argument.");
        }

        logger.info("Execution time: {}ms", System.currentTimeMillis() - start);
    }
}
